import { NgModule } from '@angular/core';
import { DragDropModule } from '@angular/cdk/drag-drop';

import * as material from '@angular/material';
import { ScrollingModule } from '@angular/cdk/scrolling';


@NgModule({
    imports: [
        DragDropModule,
        material.MatAutocompleteModule,
        material.MatBadgeModule,
        material.MatBottomSheetModule,
        material.MatButtonModule,
        material.MatButtonToggleModule,
        material.MatCardModule,
        material.MatCheckboxModule,
        material.MatChipsModule,
        material.MatStepperModule,
        material.MatDatepickerModule,
        material.MatDialogModule,
        material.MatDividerModule,
        material.MatExpansionModule,
        material.MatGridListModule,
        material.MatIconModule,
        material.MatInputModule,
        material.MatListModule,
        material.MatMenuModule,
        material.MatNativeDateModule,
        material.MatPaginatorModule,
        material.MatProgressBarModule,
        material.MatProgressSpinnerModule,
        material.MatRadioModule,
        material.MatRippleModule,
        material.MatSelectModule,
        material.MatSidenavModule,
        material.MatSliderModule,
        material.MatSlideToggleModule,
        material.MatSnackBarModule,
        material.MatSortModule,
        material.MatTableModule,
        material.MatTabsModule,
        material.MatToolbarModule,
        material.MatTooltipModule,
        material.MatTreeModule,
        ScrollingModule,
        material.MatFormFieldModule,
    ],
    exports: [
        material.MatFormFieldModule,
        DragDropModule,
        material.MatAutocompleteModule,
        material.MatBadgeModule,
        material.MatBottomSheetModule,
        material.MatButtonModule,
        material.MatButtonToggleModule,
        material.MatCardModule,
        material.MatCheckboxModule,
        material.MatChipsModule,
        material.MatStepperModule,
        material.MatDatepickerModule,
        material.MatDialogModule,
        material.MatDividerModule,
        material.MatExpansionModule,
        material.MatGridListModule,
        material.MatIconModule,
        material.MatInputModule,
        material.MatListModule,
        material.MatMenuModule,
        material.MatNativeDateModule,
        material.MatPaginatorModule,
        material.MatProgressBarModule,
        material.MatProgressSpinnerModule,
        material.MatRadioModule,
        material.MatRippleModule,
        material.MatSelectModule,
        material.MatSidenavModule,
        material.MatSliderModule,
        material.MatSlideToggleModule,
        material.MatSnackBarModule,
        material.MatSortModule,
        material.MatTableModule,
        material.MatTabsModule,
        material.MatToolbarModule,
        material.MatTooltipModule,
        material.MatTreeModule,
        ScrollingModule,
    ]
})
export class MaterialModule { }
